/**
 * generate-avatars — turns a folder of full-size avatar PNGs into app assets.
 *
 *   node scripts/generate-avatars.js <source-folder>
 *   npm run avatars -- <source-folder>
 *
 * For every `*.png` in the source folder it:
 *   1. downscales it to 256x256 with nearest-neighbour sampling, so the pixel-art
 *      blocks stay hard-edged instead of smearing;
 *   2. writes it as a palette PNG (pixel art has a handful of colours, so this
 *      takes a ~600 KB original down to a few KB) to assets/images/avatars/;
 *   3. regenerates src/constants/avatars.ts, the id -> require() map the app reads.
 *
 * The id is the file name without its extension ("avatar-042"), and it is what
 * the user's profile stores — so keep the source names stable. Renaming a file
 * orphans every profile that picked it (they fall back to the initial).
 *
 * Re-running is safe: the output folder is cleared first, so a deleted source
 * image doesn't linger in the bundle.
 */
const fs = require('fs');
const path = require('path');
const sharp = require('sharp');

const ROOT = path.resolve(__dirname, '..');
const OUT_DIR = path.join(ROOT, 'assets', 'images', 'avatars');
const MAP_FILE = path.join(ROOT, 'src', 'constants', 'avatars.ts');

/** 3x the largest on-screen size (~80pt), so it's sharp on every density. */
const SIZE = 256;

/** Has to match AvatarIdSchema in shared/types/user.types.ts. */
const ID_PATTERN = /^[a-z0-9-]+$/;

async function main() {
    const srcDir = process.argv[2];
    if (!srcDir || !fs.existsSync(srcDir)) {
        console.error('Usage: node scripts/generate-avatars.js <source-folder>');
        process.exit(1);
    }

    const files = fs.readdirSync(srcDir)
        .filter(f => f.toLowerCase().endsWith('.png'))
        .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));

    if (files.length === 0) {
        console.error(`No .png files in ${srcDir}`);
        process.exit(1);
    }

    const ids = files.map(f => path.parse(f).name.toLowerCase().replace(/[\s_]+/g, '-'));
    const bad = ids.filter(id => !ID_PATTERN.test(id));
    if (bad.length) {
        console.error(`Rename these so they are lowercase letters, digits and dashes: ${bad.join(', ')}`);
        process.exit(1);
    }

    fs.rmSync(OUT_DIR, { recursive: true, force: true });
    fs.mkdirSync(OUT_DIR, { recursive: true });

    let inBytes = 0;
    let outBytes = 0;
    const written = [];
    const skipped = [];
    for (let i = 0; i < files.length; i++) {
        const src = path.join(srcDir, files[i]);
        const dest = path.join(OUT_DIR, `${ids[i]}.png`);

        // A truncated download fails here. Skip it rather than abort the batch,
        // and leave it out of the map so the app never requires a missing file.
        try {
            await sharp(src)
                .resize(SIZE, SIZE, { kernel: 'nearest', fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
                .png({ palette: true, colours: 64, compressionLevel: 9, effort: 10 })
                .toFile(dest);
        } catch (err) {
            fs.rmSync(dest, { force: true });
            skipped.push(`${files[i]} (${err.message.split('\n')[0]})`);
            continue;
        }

        written.push(ids[i]);
        inBytes += fs.statSync(src).size;
        outBytes += fs.statSync(dest).size;
    }

    const lines = written.map(id => `    '${id}': require('../../assets/images/avatars/${id}.png'),`);
    fs.writeFileSync(MAP_FILE, `/**
 * GENERATED by scripts/generate-avatars.js — do not edit by hand. Re-run the
 * script after adding or removing avatar art.
 *
 * id -> bundled asset. Written out line by line because Metro resolves
 * \`require\` at build time, so the paths have to be literals.
 */
export const AVATAR_IMAGES: Record<string, number> = {
${lines.join('\n')}
};

/** Picker order. */
export const AVATAR_IDS = Object.keys(AVATAR_IMAGES);
`);

    const mb = n => (n / 1024 / 1024).toFixed(2);
    console.log(`${written.length} avatars: ${mb(inBytes)} MB -> ${mb(outBytes)} MB`);
    console.log(`  images: ${path.relative(ROOT, OUT_DIR)}`);
    console.log(`  map:    ${path.relative(ROOT, MAP_FILE)}`);
    if (skipped.length) {
        console.warn(`\nSkipped ${skipped.length} unreadable file(s) — re-export and run again:`);
        skipped.forEach(s => console.warn(`  ${s}`));
    }
}

main().catch(err => {
    console.error(err);
    process.exit(1);
});
